### PR TITLE
Setup devdir through --devdir parameter

### PR DESCRIPTION
**Pull request by ghostoy**

### CODE REVIEW

**Comment by rogerwang** [comment]
could you please add documentation? Thanks.

**Comment by ghostoy** [comment]
@rogerwang sure.

**Comment by ghostoy** [comment]
@rogerwang I'm just aware that there is no documents for all the parameters. `--help` is broken.

**Comment by ghostoy** [comment]
@rogerwang  Could you merge this PR and make a release for it?

**Comment by ghostoy** [comment]
@rogerwang Could you publish a new release on npmjs.com ?

**Pull request merged**
