### PR TITLE
Node gyp 3 update

### PR DESCRIPTION
**Pull request by ghostoy**
Merge with node-gyp 3.6.2 to support VS 2017.

### CODE REVIEW

**Comment by rogerwang** [comment]
Thanks. Would you just place our commits on top of upstream in your branch (just like what we did with the Chromium and v8 repo)? Then I'll just push it rather than using github PR.

**Comment by ghostoy** [comment]
@rogerwang The new branch is now in [node-gyp-3.6.2](https://github.com/nwjs/nw-gyp/tree/node-gyp-3.6.2) branch.

**Comment by rogerwang** [comment]
@ghostoy do I need to push it to npm or you'll do it?

**Comment by ghostoy** [comment]
@rogerwang Yes, please help. I don't have account of npm for publishing nw-gyp.

**Comment by rogerwang** [comment]
@ghostoy I just pushed it. And what's your npmjs.org account? I'll add you to the collaborators list.

**Pull request closed without merging**
